### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by nafitriaulia** [PINTO0309/Bazel_bin#1]
succeed

**Comment by PINTO0309** [comment]
I seem to have solved the problem safely, so I close the issue.

**Comment by mattn** [comment]
install.sh should do `chmod +x`.

**Comment by PINTO0309** [comment]
Thanks @mattn

Fixed at a023e00138b5af3edfffa30149929fc86cfabe78.

**Comment by mattn** [comment]
Thanks. It also be nice. 👍  But I meant this:

```
$ wget ... -o bazel
$ chmod +x bazel
$ sudo cp bazel /usr/local/bin/bazel
```

**Comment by PINTO0309** [comment]
@mattn 
Thank you for giving feedback.
I'm embarrassed...
Again 8f13be202b456659375a7683b339806d83fde954
