### ISSUE TITLE
Bad file descriptor on buster 27 and 28 armh builds 

### ISSUE THREAD

**Issue by snowzach** [PINTO0309/Bazel_bin#2]
**[Required]** Your device (RaspberryPi3, LaptopPC, or other device name):  
qemu on x86_64 docker
  
**[Required]** Your device's CPU architecture (armv7l, x86_64, or other architecture name):  
arm7l
  
**[Required]** Your OS (Raspbian, Ubuntu1604, or other os name):  
Debian Buster
  
**[Required]** Details of the work you did before the problem occurred:  

**[Required]** Error message:  
```
root@7a626b435c10:/tmp# ./bazel
Opening zip "/proc/self/exe": lseek(): Bad file descriptor
FATAL: Failed to open Bazel as a zip file: (error: 9): Bad file descriptor
```

**[Required]** Overview of problems and questions:  
Am I missing any packages or is there something wrong with the build maybe?

**Comment by snowzach** [comment]
Hmmm.. I think this has something to do with running qemu/docker. I just tried this on my raspberry pi and it seemed to work.

**Comment by snowzach** [comment]
Okay, I figured it out. I am using Docker and Qemu to build this and for whatever reason the `/proc/self/exe` auto-symlink thing doesn't work inside of docker. 

I was able to fix this by editing the bazel executable with sed and replaced it with a string of equal length that was in the path... it just so happens /usr/bin/bazel is the same length as /proc/self/exe
```
sed -i 's@/proc/self/exe@/usr/bin/bazel@' bazel
```
I then installed it to /usr/bin/bazel and it works.

**Comment by PINTO0309** [comment]
@snowzach 
Thank you for your feedback. I performed the following steps that you taught me and executed Bazel. A Segmentation Fault occurred. I tried to run the same command against the compiled "bazel" binary.

```bash
sed -i 's@/proc/self/exe@/usr/bin/bazel@' bazel
```

**Comment by snowzach** [comment]
Thanks for looking. This appears to be another qemu issue. I upgraded to qemu 4.1.0 and this issue went away. Another issue popped up. 
```
# ./bazel
Extracting Bazel installation...
Cannot enumerate embedded binaries:  (Value too large for defined data type)
```
Oh well, I'll keep trying to figure it out.

**Comment by PINTO0309** [comment]
I have also been experiencing errors for two months, just like you.
QEMU 4.0.0 + chroot
![Screenshot 2019-08-16 11:42:35](https://user-images.githubusercontent.com/33194443/63139909-fe524d00-c01a-11e9-8722-348012805f44.png)
