### ISSUE TITLE
On what platform do you build bazel

### ISSUE THREAD

**Issue by johncblacker** [PINTO0309/Bazel_bin#3]
On what platform do you build your bazel distro's?  I've been trying to build on a rPi3b+ and having problems with running out of resources - heap.  I've tried adjusting the java options but can't find anything that works.  I have a 3.7.2 version of bazel from "bazel-bin" and have problems with building mediapipe from latest source with a symbol not defined error at runtime.  So, if you could help me out I'd appreciate it.

**Comment by PINTO0309** [comment]
>On what platform do you build your bazel distro's?

RaspberryPi4 or Cross-compilation https://github.com/PINTO0309/pytorch4raspberrypi

>and have problems with building mediapipe from latest source with a symbol not defined error at runtime.

I don't know what OS you are using. MediaPipe does not support **`armv7l`**.

**Comment by johncblacker** [comment]
So, I’m told by mediapipe support; however, they blame the error building mediapipe on TFlite (duh, I do believe this is another Google offering).

I submitted a feature request to support the mediapipe build on rPi 3 and 4.  As I look into the mediapipe build info, it requests bazel 3.7.2 at least,

so since I’m running the bazel-bin 3.7.2 it should work, but mediapipe support claims the undeclared symbol is because TFlite issue.  However, TFlite

is supported on raspberry pi 3 and 4 via coral.  So what’s up with that excuse?
